# Generated by Django 2.0.3 on 2018-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='userImg',
            field=models.ImageField(default='media/default-img.png', upload_to='media'),
        ),
    ]
