# Generated by Django 2.0.2 on 2018-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarBrand', models.CharField(max_length=45)),
                ('Year', models.IntegerField(max_length=10)),
                ('Engine', models.IntegerField(max_length=10)),
                ('Cylinders', models.CharField(max_length=16)),
                ('Doors', models.IntegerField(max_length=10)),
                ('Weight', models.IntegerField(max_length=10)),
                ('Fuel', models.CharField(max_length=15)),
                ('BodyType', models.CharField(max_length=20)),
                ('Transmission', models.CharField(max_length=45)),
                ('HP', models.IntegerField(max_length=10)),
                ('TopSpeed', models.IntegerField(max_length=10)),
                ('FuelCapacity', models.IntegerField(max_length=10)),
                ('Country', models.CharField(max_length=45)),
                ('Mileage', models.IntegerField(max_length=45)),
                ('Color', models.CharField(max_length=45)),
            ],
        ),
    ]
