# Generated by Django 2.0.2 on 2018-03-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='Doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Engine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='FuelCapacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='HP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='TopSpeed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
