# Generated by Django 2.0.2 on 2018-03-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20180319_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='HP',
        ),
    ]
