# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carmodel_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name_plural': 'Car Models'},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='CarImg',
            field=models.CharField(default=django.utils.timezone.now, max_length=50000),
            preserve_default=False,
        ),
    ]
