# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_administrator_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='CarImg',
            field=models.FileField(upload_to=''),
        ),
    ]
