# Generated by Django 2.0.3 on 2018-04-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20180328_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
    ]
