# Generated by Django 2.0.2 on 2018-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20180328_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='CarImg',
            field=models.CharField(max_length=50000),
        ),
    ]
