# Generated by Django 2.0.2 on 2018-03-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20180328_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
