# Generated by Django 2.0.3 on 2018-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20180406_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='CarImg',
            field=models.ImageField(default=1, upload_to='media'),
        ),
    ]
