# Generated by Django 2.0.3 on 2018-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20180505_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='CarImg',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
