# Generated by Django 2.0.3 on 2018-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20180505_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='CarImg',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
