# Generated by Django 2.0.3 on 2018-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20180505_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='DoorsNum',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Engine',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='FuelCapacity',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='HP',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Mileage',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='TopSpeed',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Year',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='BodyType',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='CarBrand',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Color',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Country',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Cylinders',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Fuel',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Model',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Transmission',
            field=models.CharField(max_length=5000),
        ),
    ]
