# Generated by Django 2.0.3 on 2018-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20180505_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='DoorsNum',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Engine',
            field=models.FloatField(default=1.6),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='FuelCapacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='HP',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='TopSpeed',
            field=models.IntegerField(default=220),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Weight',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Year',
            field=models.IntegerField(default=2018),
        ),
    ]
