# Generated by Django 2.0.3 on 2018-05-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20180505_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='DoorsNum',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Engine',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='FuelCapacity',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='HP',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Mileage',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='TopSpeed',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='Year',
        ),
    ]
