# Generated by Django 2.0.3 on 2018-05-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20180505_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='DoorsNum',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Engine',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='FuelCapacity',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='HP',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Mileage',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='TopSpeed',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Weight',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='Year',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
