# Generated by Django 2.0.3 on 2018-05-05 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20180505_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='DoorsNum',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Engine',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='FuelCapacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='HP',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='TopSpeed',
            field=models.IntegerField(default=220),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Weight',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='Year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
