# Generated by Django 2.0.3 on 2018-05-05 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20180505_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='Year',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
