# Generated by Django 2.0.3 on 2018-04-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='year',
        ),
    ]
