# Generated by Django 2.0.3 on 2018-04-21 19:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20180406_1837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdrive', '0002_auto_20180421_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdmodel',
            name='carName',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='Drive Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='Drive Time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='driveCar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_of', to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='driver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
