# Generated by Django 2.0.3 on 2018-04-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0003_auto_20180421_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdmodel',
            name='driveCar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_of', to='cars.CarModel'),
        ),
    ]
