# Generated by Django 2.0.3 on 2018-04-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0004_auto_20180421_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdmodel',
            name='driver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
