# Generated by Django 2.0.3 on 2018-04-21 20:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0007_auto_20180421_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdmodel',
            name='Drive Date',
        ),
        migrations.RemoveField(
            model_name='tdmodel',
            name='Drive Time',
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='driveDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Test Drive Date'),
        ),
        migrations.AlterField(
            model_name='tdmodel',
            name='driveCar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel'),
        ),
        migrations.AlterField(
            model_name='tdmodel',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
