# Generated by Django 2.0.3 on 2018-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='userImg',
            field=models.ImageField(default=1, upload_to='media'),
        ),
    ]
